language: php
install:
  - composer install
  - mv config/config.travis.php config/config.php
before_script:
  - mysql -e 'create database app_test;'
  - psql -c 'create database app_test' -U postgres
script: php tests/test.php
matrix:
  allow_failures:
    - env: DB=sqlite
  fast_finish: true
  include:
    # MariaDB
    - php: 5.5
      env: DB=mariadb
      addons:
        mariadb: '10.1'
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: '10.1'
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: '10.1'
    # MySQL
    - php: 5.5
      env: DB=mysql
      services:
        - mysql
    - php: 5.6
      env: DB=mysql
      services:
        - mysql
    - php: 7.0
      env: DB=mysql
      services:
        - mysql
    # PostgreSQL
    - php: 5.5
      env: DB=postgresql
      services:
        - postgresql
    - php: 5.6
      env: DB=postgresql
      services:
        - postgresql
    - php: 7.0
      env: DB=postgresql
      services:
        - postgresql
    # SQLite
    - php: 5.5
      env: DB=sqlite
    - php: 5.6
      env: DB=sqlite
    - php: 7.0
      env: DB=sqlite

